"use client";

import { useEffect, useState } from "react";
import { Card, ErrorState, Label, Skeleton, StatusDot } from "./ui";
import { fmtCountdown } from "@/lib/format";
import { FUNCTIONS, type FunctionStates, type LicenseStatusResponse } from "@/lib/types";

/** Realtime tab — application-level status only. No game data, ever. */
export function RealtimeTab({
  status, loading, error, onRetry,
}: {
  status: LicenseStatusResponse | null;
  loading: boolean;
  error: string | null;
  onRetry: () => void;
}) {
  const [nowMs, setNowMs] = useState(() => Date.now());
  useEffect(() => {
    const t = setInterval(() => setNowMs(Date.now()), 1000);
    return () => clearInterval(t);
  }, []);

  if (loading) {
    return (
      <div className="space-y-3">
        <Skeleton className="h-20 w-full" />
        <Skeleton className="h-56 w-full" />
        <Skeleton className="h-40 w-full" />
      </div>
    );
  }
  if (error || !status) return <ErrorState message={error ?? "Couldn't load realtime status."} onRetry={onRetry} />;

  const licenseOk = status.license.status === "ACTIVE";
  const remaining = new Date(status.session_expires_at).getTime() - nowMs;

  return (
    <div className="space-y-4">
      <div className="pt-1">
        <h1 className="text-[22px] font-black">Realtime</h1>
        <p className="mt-0.5 text-[12px] text-slate-400">Live app status — generated by Zev itself.</p>
      </div>

      <Card className="space-y-2.5">
        <div className="flex items-center justify-between text-[13px]">
          <span className="text-slate-400">SYSTEM STATUS</span>
          <span className="flex items-center gap-1.5 font-bold text-emerald-300"><StatusDot on /> ONLINE</span>
        </div>
        <div className="flex items-center justify-between text-[13px]">
          <span className="text-slate-400">LICENSE</span>
          <span className="flex items-center gap-1.5 font-bold text-emerald-300"><StatusDot on={licenseOk} /> {licenseOk ? "VALID" : status.license.status}</span>
        </div>
        <div className="flex items-center justify-between text-[13px]">
          <span className="text-slate-400">SESSION</span>
          <span className="font-mono font-bold text-cyan-300">{fmtCountdown(remaining)}</span>
        </div>
      </Card>

      <Card>
        <Label>FUNCTION STATUS</Label>
        <div className="mt-2 divide-y divide-white/5">
          {FUNCTIONS.map((f) => {
            const on = status.functions[f.key as keyof FunctionStates];
            return (
              <div key={f.key} className="flex items-center justify-between py-2 text-[13px]">
                <span className="text-slate-300">{f.name}</span>
                <span className="flex items-center gap-1.5 font-bold">
                  <StatusDot on={on} />
                  <span className={on ? "text-emerald-300" : "text-slate-500"}>{on ? "ON" : "OFF"}</span>
                </span>
              </div>
            );
          })}
        </div>
      </Card>

      <p className="pb-2 text-center text-[11px] text-slate-600">
        Status is generated by the Zev app itself · no game data
      </p>
    </div>
  );
}
