/**
 * Builds the THREE canonical .mobileconfig files using the real serializer
 * in src/lib/mobileconfig.ts (no second serializer, no copy-paste).
 *
 * Outputs:
 *   src/mobileconfig/profiles/zev-lock-<preset>.mobileconfig  (canonical files)
 *   src/mobileconfig/profiles/bytes.ts                        (generated byte mirror
 *     used ONLY to serve the exact same bytes from the API at runtime,
 *     where filesystem reads are unavailable — verified byte-identical by tests)
 *
 * Run:  npx --yes tsx scripts/build-mobileconfig.mts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import {
  PROFILE_PRESETS,
  buildMobileconfig,
  validateMobileconfig,
  type ProfilePreset,
} from "../src/lib/mobileconfig.ts";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outDir = join(root, "src", "mobileconfig", "profiles");
mkdirSync(outDir, { recursive: true });

const APP_ORIGIN = "https://zevlock.app";

function sha256(s: string): string {
  return createHash("sha256").update(s, "utf8").digest("hex");
}

function tsString(s: string): string {
  return JSON.stringify(s);
}

const entries: string[] = [];
let failed = false;

for (const preset of PROFILE_PRESETS as readonly ProfilePreset[]) {
  const built = buildMobileconfig({ preset, origin: APP_ORIGIN });
  const check = validateMobileconfig(built.xml, preset);
  if (!check.ok) {
    console.error(`VALIDATION FAILED for ${preset}: ${check.errors.join("; ")}`);
    failed = true;
    continue;
  }
  const filePath = join(outDir, built.filename);
  writeFileSync(filePath, built.xml, "utf8");
  const size = Buffer.byteLength(built.xml, "utf8");
  console.log(`${built.filename}\n  size=${size} sha256=${sha256(built.xml)}\n  uuid=${built.payloadUUID}`);
  entries.push(
    `  ${tsString(preset)}: {\n` +
      `    id: ${tsString(preset)},\n` +
      `    filename: ${tsString(built.filename)},\n` +
      `    uuid: ${tsString(built.payloadUUID)},\n` +
      `    identifier: ${tsString(built.payloadIdentifier)},\n` +
      `    xml: ${tsString(built.xml)},\n` +
      `  },`
  );
}

if (failed) {
  console.error("Aborted: a profile failed validation.");
  process.exit(1);
}

const moduleSrc =
  `// AUTO-GENERATED by scripts/build-mobileconfig.mts — do not edit by hand.\n` +
  `// Byte mirror of src/mobileconfig/profiles/*.mobileconfig so the API can serve\n` +
  `// the exact canonical bytes at runtime. Tests assert byte-identity.\n` +
  `export interface CanonicalProfile {\n` +
  `  id: string;\n` +
  `  filename: string;\n` +
  `  uuid: string;\n` +
  `  identifier: string;\n` +
  `  xml: string;\n` +
  `}\n` +
  `export const CANONICAL_IDS = ${tsString([...PROFILE_PRESETS])} as unknown as string[];\n` +
  `export const CANONICAL_PROFILES: Record<string, CanonicalProfile> = {\n${entries.join("\n")}\n};\n`;
writeFileSync(join(outDir, "bytes.ts"), moduleSrc, "utf8");
console.log("bytes.ts written");
